base/apis/urls.py
from django.urls import path


from .views import SponsorPreferenceList, SponsorPreferenceDetail
from .import views

urlpatterns = [
    path("", SponsorPreferenceList.as_view()),
    path("<int:pk>/", SponsorPreferenceDetail.as_view()),
    path('create_user/', views.create_user, name='create_user'),
    path('create_details/', views.create_details, name='create_details'),
    path('create_fam_education/', views.create_fam_education, name='create_fam_education'),

]

base/base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('u_educ_site.urls')),
    path('apis/', include('apis.urls'))
]

base/u_educ_site/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MinValueValidator
from django.utils.timezone import now
import os
from math import ceil


# Create your models here.
class Role(models.Model):
    role = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    description = models.TextField(null=True, blank=True)
    updated = models.DateField(auto_now=True)
    updated = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} -> {self.role}'
    
class SponsorPreferences(models.Model):
    firstName = models.CharField(max_length=200)
    lastName = models.CharField(max_length=200)
    email = models.EmailField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    phoneNumber = models.CharField(max_length=15, blank=True, null=True)
    address = models.CharField(max_length=300, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    zipCode = models.CharField(max_length=20, blank=True, null=True)

    preferred_student_gender = models.CharField(max_length=10, choices=[
        ('male', 'Male'),
        ('female', 'Female'),
        ('any', 'Any'),
    ], default='any', help_text="Preferred gender of the student.")

    preferred_student_courses = models.CharField(max_length=20, choices=[
        ('sciences', 'Sciences'),
        ('arts', 'Arts'),
        ('any', 'Any'),
    ], default='any', help_text="Preferred course of study for the student.")

    tuition_amount_min = models.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        validators=[MinValueValidator(0)], 
        blank=True, 
        null=True,
        help_text="Minimum tuition amount the sponsor is willing to provide."
    )
    tuition_amount_max = models.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        validators=[MinValueValidator(0)], 
        blank=True, 
        null=True,
        help_text="Maximum tuition amount the sponsor is willing to provide."
    )


    weight_student_gender = models.DecimalField(max_digits=5, decimal_places=2, default=0.0)
    weight_student_courses = models.DecimalField(max_digits=5, decimal_places=2, default=0.0)
    weight_tuition = models.FloatField(default=0.0)

    profileImage = models.ImageField(upload_to = 'profile_images/', blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.firstName} {self.lastName} ({self.email})'
    
    def calculate_tuition_weight(self):
        if self.tuition_amount_min is not None and self.tuition_amount_max is not None:
            range_tuition = self.tuition_amount_max - self.tuition_amount_min
            weight = range_tuition / (self.tuition_amount_max + self.tuition_amount_min)
            return weight
        return 0.0   

    def calculate_weights(self):
        if self.preferred_student_gender == 'female':
            self.weight_student_gender = 1.0
        else:
            self.weight_student_gender = 0.5

        if self.preferred_student_courses == 'sciences':
            self.weight_student_courses = 1.0
        else:
            self.weight_student_courses = 0.8
        
        self.weight_tuition = self.calculate_tuition_weight()

        self.save()

    def average_weight(self):
        weights = [self.weight_student_gender, self.weight_student_courses, self.weight_tuition]
        my_average_weight = sum(weights) / len(weights)
        rounded_average_weight = round(my_average_weight, 3)
        return (abs(rounded_average_weight))
    
class Mappings(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Accepted', 'Accepted'),
        ('Rejected', 'Rejected'),
    )
    sponsor = models.ForeignKey(User, on_delete=models.CASCADE)
    studentFullName = models.CharField(max_length=500)
    studentEmail = models.EmailField()
    studentGender = models.TextField(max_length=15, blank=True)
    yearOfStudy = models.CharField(max_length=10, blank=True)
    tuitionAmountPerSemester = models.CharField(max_length=20, blank=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)

    def __str__ (self):
        return f'{self.sponsor} -> {self.studentFullName}'

base/templates/my_admin/admin_base.html
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'home/img/apple-icon.png' %}">
    <link rel="icon" type="image/png" href="{% static 'home/img/favicon.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
      Admin Dashboard
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <!-- CSS Files -->
    <link href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'home/css/paper-dashboard.css' %}" rel="stylesheet" />

    <style>
      .inactive {
          opacity: 0.5;
          pointer-events: none;
      }
  </style>

  </head>

<body class="">
    {% include 'my_admin/admin_navbar.html' %}
    {% include 'my_admin/admin_sidebar.html' %}

    <div class="wrapper">
      {% block content %}

        <!--   Core JS Files   -->
        <script src="{% static 'home/js/core/jquery.min.js' %}"></script>
        <script src="{% static 'home/js/core/popper.min.js' %}"></script>
        <script src="{% static 'home/js/core/bootstrap.min.js' %}"></script>
        <script src="{% static 'home/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
        <!--  Google Maps Plugin    -->
        <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
        <!-- Chart JS -->
        <script src="{% static 'home/js/plugins/chartjs.min.js'%}"></script>
        <!--  Notifications Plugin    -->
        <script src="{% static 'home/js/plugins/bootstrap-notify.js' %}"></script>
        <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
          <script src="{% static 'home/js/paper-dashboard.min.js' %}" type="text/javascript"></script>
        <script>

          $(document).ready(function() {
            // Javascript method's body can be found in assets/assets-for-demo/js/demo.js
            demo.initChartsPages();
          });
        </script>
            
    {% endblock %}
    </div>

</body>

</html>

base/templates/my_admin/admin_dashboard.html
{% extends 'my_admin/admin_base.html' %}
{% load static %}

{% block content %}
  {% if user_role.role != 'Sponsor' %}
    <div class="main-panel">
        <div class="content">
          <div class="row">
              <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="card card-stats">
                  <div class="card-body ">
                    <div class="row">
                      <div class="col-5 col-md-4">
                        <div class="icon-big text-center icon-warning">
                          <i class="fa fa-user-circle text-warning"></i>
                        </div>
                      </div>
                      <div class="col-7 col-md-8">
                        <div class="numbers">
                          <p class="card-category">Student No</p>
                          <p class="card-title">{{ student_count }}<p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="card-footer ">
                    <hr>
                    <div class="stats">
                      <i class="fa fa-user"></i>
                      Student Number
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="card card-stats">
                  <div class="card-body ">
                    <div class="row">
                      <div class="col-5 col-md-4">
                        <div class="icon-big text-center icon-warning">
                          <i class="nc-icon nc-money-coins text-success"></i>
                        </div>
                      </div>
                      <div class="col-7 col-md-8">
                        <div class="numbers">
                          <p class="card-category">Sponsor No</p>
                          <p class="card-title">{{ sponsor_count }}<p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="card-footer ">
                    <hr>
                    <div class="stats">
                      <i class="nc-icon nc-money-coins"></i>
                      Total Sponsors
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="card card-stats">
                  <div class="card-body ">
                    <div class="row">
                      <div class="col-5 col-md-4">
                        <div class="icon-big text-center icon-warning">
                          <i class="fa fa-hourglass-half text-danger"></i>
                        </div>
                      </div>
                      <div class="col-7 col-md-8">
                        <div class="numbers">
                          <p class="card-category">Pending</p>
                          <p class="card-title">{{ pending_mappings_count }}<p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="card-footer ">
                    <hr>
                    <div class="stats">
                      <i class="fa fa-hourglass"></i>
                      Pending Mappings
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="card card-stats">
                  <div class="card-body ">
                    <div class="row">
                      <div class="col-5 col-md-4">
                        <div class="icon-big text-center icon-warning">
                          <i class="nc-icon nc-favourite-28 text-primary"></i>
                        </div>
                      </div>
                      <div class="col-7 col-md-8">
                        <div class="numbers">
                          <p class="card-category">Active</p>
                          <p class="card-title">{{ active_mappings_count }}<p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="card-footer ">
                    <hr>
                    <div class="stats">
                      <i class="fa fa-bell"></i>
                      Active Mappings
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-6 col-md-12">
                <div class="card">
                  <div class="card-header">
                    <h4 class="card-title">Sponsors</h4>
                    <p class="card-category">List of all sponsors</p>
                  </div>
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table">
                        <thead class=" text-primary">
                          <th>Name</th>
                          <th>Email</th>
                          <th>Actions</th>
                        </thead>
                        <tbody>
                          {% for sponsor in sponsors %}
                            <tr>
                              <td>{{ sponsor.firstName }}</td>
                              <td>{{ sponsor.email }}</td>
                              <td>
                                <a href="{% url 'admin_view_sponsor' sponsor.id %}" class="btn btn-info btn-sm">View</a>
                              </td>
                            </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-6 col-md-12">
                <div class="card">
                  <div class="card-header">
                    <h4 class="card-title">Students</h4>
                    <p class="card-category">List of all students</p>
                  </div>
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table">
                        <thead class=" text-primary">
                          <th>Name</th>
                          <th>Email</th>
                          <th>Actions</th>
                        </thead>
                        <tbody>
                          {% for student_data in students_data %}
                            <tr>
                              <td>{{ student_data.student.fullName }}</td>
                              <td>{{ student_data.student.email }}</td>
                              <td>
                                <a href="{% url 'admin_view_student' student_data.student.id %}" class="btn btn-info btn-sm">View</a>
                              </td>
                            </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
  {% endif %}
{% endblock %}

base/templates/my_admin/admin_map_requests.html
{% extends 'my_admin/admin_base.html' %}
{% load static %}

{% block content %}
<div class="main-panel">
    <div class="content">
        <div class="row">
          
          <div class="col-md-12">
            <div class="card card-plain">
              <div class="card-header">
                <h4 class="card-title"> Pending Mapping Requests</h4>
                <p class="card-category"> Below are the pending map requests from sponsors</p>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead class="text-primary">
                            <tr>
                                <th>Sponsor Name</th>
                                <th>Student Name</th>
                                <th>Gender</th>
                                <th>Year Of Study</th>
                                <th>Tution Amount</th>   
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for mapping in pending_mappings %}
                            <tr>
                                <td>{{ mapping.sponsor }}</td>
                                <td>{{ mapping.studentFullName }}</td>
                                <td>{{ mapping.studentGender }}</td>
                                <td>{{ mapping.yearOfStudy }}</td>
                                <td>{{ mapping.tuitionAmountPerSemester }}</td>
                                <td>{{ mapping.status }}</td>
                                <td>
                                  <a href="{% url 'accept_mapping' mapping.id %}">
                                    <button class="btn btn-primary btn-sm"><i class="fa fa-check"></i> Accept</button>
                                  </a>
                                  <a href="{% url 'deny_mapping' mapping.id %}">
                                    <button class="btn btn-danger btn-sm"><i class="fa fa-times"></i> Deny</button>
                                  </a>
                                </td>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
            
            </div>
          </div>
        </div>
      </div>
</div>


{% endblock %}

base/templates/my_admin/admin_mapping.html
{% extends 'my_admin/admin_base.html' %}
{% load static %}

{% block content %}
<div class="main-panel">
    <div class="content">
        <div class="row">
          
          <div class="col-md-12">
            <div class="card card-plain">
              <div class="card-header">
                <h4 class="card-title"> Active Mappings of Sponsors & Students</h4>
                <p class="card-category"> Below are the pending map requests from sponsors</p>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead class="text-primary">
                            <tr>
                                <th>Sponsor Name</th>
                                <th>Student Name</th>
                                <th>Gender</th>
                                <th>Year Of Study</th>
                                <th>Tution Amount</th>   
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for mapping in active_mappings %}
                            <tr>
                                <td>{{ mapping.sponsor }}</td>
                                <td>{{ mapping.studentFullName }}</td>
                                <td>{{ mapping.studentGender }}</td>
                                <td>{{ mapping.yearOfStudy }}</td>
                                <td>{{ mapping.tuitionAmountPerSemester }}</td>
                                <td>{{ mapping.status }}</td>
                                <td>
                                    <a href="#"><button class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Delete</button></a>
                                </td>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
            
            </div>
          </div>
        </div>
      </div>
</div>


{% endblock %}

base/templates/my_admin/admin_navbar.html
{% load static %}

    <div class="main-panel {% if inactive_sidebar %}inactive{% endif %}">
    <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="{% url 'home' %}">{{ page_title }}</a>
          </div>

          <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <ul class="navbar-nav">
              <li class="nav-item btn-rotate dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="nc-icon nc-bell-55"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Some Actions</span>
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link btn-rotate" href="javascript:;">
                  <i class="nc-icon nc-settings-gear-65"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Account</span>
                  </p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>

base/templates/my_admin/admin_sidebar.html
{% load static %}
{% if request.user.role != 'Sponsor' %}
    <div class="sidebar {% if inactive_sidebar %}inactive{% endif %}" data-color="white" data-active-color="danger">
        <div class="logo">
          <a href="{% url 'admin_dashboard' %}" class="simple-text logo-mini">
            <div class="logo-image-small">
              <img src="{% static 'home/img/logo-small.png' %}">
            </div>
          </a>
          <a href="{% url 'admin_dashboard' %}" class="simple-text logo-normal">
            {{request.user}} Admin
          </a>
        </div>

        <div class="sidebar-wrapper">
          <ul class="nav">
            <li class="{% if request.resolver_match.url_name == 'admin_dashboard' %}active{% endif %}">
              <a href="{% url 'admin_dashboard' %}">
                <i class="nc-icon nc-bank"></i>
                <p>Dashboard</p>
              </a>
            </li>
            <li class="{% if request.resolver_match.url_name == 'admin_mappings' %}active{% endif %}">
              <a href="{% url 'admin_mappings' %}">
                <i class="nc-icon nc-money-coins"></i>
                <p>Mappings</p>
              </a>
            </li>
            <li class="{% if request.resolver_match.url_name == 'admin_map_requests' %}active{% endif %}">
              <a href="{% url 'admin_map_requests' %}">
                <i class="fa fa-question-circle"></i>
                <p>Mapping Requests</p>
              </a>
            </li>
            <!-- <li class="{% if request.resolver_match.url_name == 'profile' %}active{% endif %}">
              <a href="{% url 'profile' %}">
                <i class="nc-icon nc-single-02"></i>
                <p>User Profile</p>
              </a>
            </li> -->
            <li>
              <a href="{% url 'logout' %}">
                <i class="nc-icon nc-user-run"></i>
                <p>Logout</p>
              </a>
            </li>
          </ul>
        </div>
      </div>
{% endif %}

base/templates/my_admin/view_sponsor.html
{% extends 'my_admin/admin_base.html' %}
{% load static %}

{% block content %}
<div class="main-panel">
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">{{ page_title }}</h4>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="#">
                            {% csrf_token %}
                            <input type="hidden" name="sponsor_id" value="{{ sponsor.id }}">
                            <div class="text-center mb-3">
                                <div class=" overflow-hidden mx-auto" style="width: 200px; height: 200px;">
                                    {% if sponsor.profileImage %}
                                        <img src="{{ sponsor.profileImage.url }}" alt="Profile Image" style="max-width: 100%; max-height: 100%; object-fit: cover;">
                                    {% else %}
                                        <div class="bg-light d-flex justify-content-center align-items-center" style="width: 100%; height: 100%;">
                                            <span class="text-secondary">No Image</span>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="sponsor_name">Sponsor Name</label>
                                <input type="text" id="sponsor_name" class="form-control" value="{{ sponsor.firstName }} {{ sponsor.lastName }}" readonly>
                            </div>

                            <div class="form-group">
                                <label for="sponsor_email">Email</label>
                                <input type="text" id="sponsor_email" class="form-control" value="{{ sponsor.email }}" readonly>
                            </div>

                            <div class="form-group">
                                <label for="sponsor_phone">Phone Number</label>
                                <input type="text" id="sponsor_phone" class="form-control" value="{{ sponsor.phoneNumber }}" readonly>
                            </div>

                            <div class="form-group">
                                <label for="sponsor_address">Address</label>
                                <input type="text" id="sponsor_address" class="form-control" value="{{ sponsor.address }}" readonly>
                            </div>

                            <div class="form-group">
                                <label for="sponsor_city">City</label>
                                <input type="text" id="sponsor_city" class="form-control" value="{{ sponsor.city }}" readonly>
                            </div>

                            <div class="form-group">
                                <label for="sponsor_state">State</label>
                                <input type="text" id="sponsor_state" class="form-control" value="{{ sponsor.state }}" readonly>
                            </div>

                            <div class="form-group">
                                <label for="sponsor_country">Country</label>
                                <input type="text" id="sponsor_country" class="form-control" value="{{ sponsor.country }}" readonly>
                            </div>

                            <div class="form-group">
                                <label for="sponsor_zip_code">Zip Code</label>
                                <input type="text" id="sponsor_zip_code" class="form-control" value="{{ sponsor.zipCode }}" readonly>
                            </div>

                            <div class="form-group">
                                <label for="preferred_student_gender">Preferred Student Gender</label>
                                <input type="text" id="preferred_student_gender" class="form-control" value="{{ sponsor.get_preferred_student_gender_display }}" readonly>
                            </div>

                            <div class="form-group">
                                <label for="preferred_student_courses">Preferred Student Courses</label>
                                <input type="text" id="preferred_student_courses" class="form-control" value="{{ sponsor.get_preferred_student_courses_display }}" readonly>
                            </div>

                            <div class="form-group">
                                <label for="tuition_amount_min">Minimum Tuition Amount</label>
                                <input type="text" id="tuition_amount_min" class="form-control" value="{{ sponsor.tuition_amount_min }}" readonly>
                            </div>

                            <div class="form-group">
                                <label for="tuition_amount_max">Maximum Tuition Amount</label>
                                <input type="text" id="tuition_amount_max" class="form-control" value="{{ sponsor.tuition_amount_max }}" readonly>
                            </div>

                            <!-- <div class="form-group">
                                <label for="average_weight">Average Weight</label>
                                <input type="text" id="average_weight" class="form-control" value="" readonly>
                            </div> -->

                            <div class="form-group">
                                <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Go Back</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}